version: '3.9'

services:

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    labels:
      NAME: rabbitmq
    image: rabbitmq:3.9.29-management
    ports:
      - "15672:15672"
      - "5672:5672"

  loggerms:
    container_name: loggerms
    build:
      context: ./loggerMS
    volumes:
      - loggerMS:/app
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  loginfoms:
    container_name: loginfoms
    build:
      context: ./logInfoMS
    volumes:
      - logInfoMS:/app
    depends_on:
      - rabbitmq

  logwarninganderrorms:
    container_name: logwarninganderrorms
    build:
      context: ./logWarningAndErrorMS
    volumes:
      - logWarningAndErrorMS:/app
    depends_on:
      - rabbitmq

volumes:
  express:
  logWarningAndErrorMS:
  logInfoMS:
  loggerMS: